apiVersion: v1
kind: Service
metadata:
  name: django-messaging-app-service
  labels:
    app: django-messaging-app
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: django-messaging-app
    version: blue
  # To switch traffic to green version, change the selector to:
  # version: green
  # Then apply: kubectl apply -f kubeservice.yaml
